name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install dependencies and build your website if needed
      # - run: npm install
      # - run: npm run build
      # Add custom domain information to ensure it's not removed
      - name: Set up custom domain
        run: |
          echo 'tinymlhack.com' > ./public/CNAME
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
